<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ApplicationIcon>app_icon.ico</ApplicationIcon>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.102.2" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <None Remove="app_icon.ico" />
      <Resource Include="app_icon.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

</Project>
